export interface FilterVenueDto {
    filter?: string | null,
    name?: string | null,
    description?: string | null,
    pdfDescription?: string | null,
    reviewCountFrom?: number | null,
    reviewCountTo?: number | null,
    ratingPerformanceFrom?: number | null,
    ratingPerformanceTo?: number | null,
    ratingAmbientFrom?: number | null,
    ratingAmbientTo?: number | null,
    ratingVenueFrom?: number | null,
    ratingVenueTo?: number | null,
    ratingOverallImpressionFrom?: number | null,
    ratingOverallImpressionTo?: number | null,
    operator?: 'AND' | 'OR',
    sortDirection?: 'asc' | 'desc',
}
